### ISSUE TITLE
cracked, ritual and hefty pots and perfume bottle not being given

### ISSUE THREAD

**Issue by Gabsan15** [The-Grand-Archives/Elden-Ring-CT-TGA#113] opened 2024-08-09 20:05 UTC
Wether it's in the "give all hefty pots", "give all build starting items" or even in the normal item give where you have to specify the item name, it doesn't give you any of the pots and perfume bottle. The normal "item give" seems to recognize it's name, but doesn't give you the item when you click on "give item". Thanks in advance for reading this and thanks for maintaining The Grand Archives.

**Comment by inuNorii** [comment] 2024-08-09 20:06
Another duplicate of #101

**Closed by inuNorii** 2024-08-09 20:06 UTC
