### ISSUE TITLE
Item gib doesn't seem to work for some items even on latest release 1.14.1

### ISSUE THREAD

**Issue by Sage420b** [The-Grand-Archives/Elden-Ring-CT-TGA#105] opened 2024-08-01 00:12 UTC
Cracked/Hefty/Ritual & perfume bottle containers all seem to not be working.
ive seen this issue apparently someone else reported it and was fixed but doesn't seem like it.

**Comment by inuNorii** [comment] 2024-08-01 07:31
Duplicate of #101

**Closed by inuNorii** 2024-08-01 07:31 UTC
